#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifdef CBA_LOCAL_DEV
#include "BuildStamp.h" // generated by CMake's cba_gen_buildstamp target
#endif
#include "Shared.h"
#include "ColorMatrix.h"
#include "ColorEffectController.h"
#include "WindowMode.h"
#include "Settings.h"
#include "ParameterRegistry.h"
#include "FeatureModule.h"
#include "FilterLayers.h"
#include "CbaIcon.h"
#include "HybridScanner.h"
#include "ColorMath.h"
#include "Theme.h"
#include "L10n.h"
#include "UIState.h"
#include "MainWindow.h"
#include "SensorGraphHUD.h"
#include "FilterLab.h"
#include "VisionLab.h"
#include "SafeStartGate.h"
#include "CreditsDialog.h"

#include <imgui.h>
#include <imgui_internal.h>
#include <chrono>
#include <array>
#include <cstdio>
#include <string>
#include <cmath>
#include <algorithm>
#include <thread>
#include <atomic>
#include <mutex>
#include <filesystem>
#include <vector>

using namespace cba;

namespace
{
	AddonDefinition AddonDef{};
}

namespace cba
{
	AddonVersion GetAddonVersion()
	{
		return AddonDef.Version;
	}
}

namespace
{
	std::chrono::steady_clock::time_point s_lastApply{};
	MAGCOLOREFFECT s_lastAppliedEffect{};
	bool s_hasApplied = false;
	std::mutex s_recomputeMutex;

	std::atomic<bool> s_watchdogRunning{false};
	std::thread s_watchdogThread;

	bool RoughlyEqual(const MAGCOLOREFFECT& a, const MAGCOLOREFFECT& b)
	{
		for (int i = 0; i < 5; i++)
			for (int j = 0; j < 5; j++)
				if (std::fabs(a.transform[i][j] - b.transform[i][j]) > 0.0005f)
					return false;
		return true;
	}

	// Only clears the s_hasApplied bookkeeping if the OS actually accepted
	// the identity-matrix Clear() call. A single rejected/failed
	// MagSetFullscreenColorEffect (transient DWM state - genuinely happens in
	// exclusive fullscreen per Emi's testing 2026-09-09, see CLAUDE.md) must
	// NOT be recorded as "cleared", or nothing ever retries it and the color
	// effect can be left stuck visibly on screen even though every UI control
	// (the ON/OFF toggle, Reset Filter, etc.) correctly believes the filter
	// is off. Replaces ~8 call sites that used to do
	// "controller.Clear(); s_hasApplied = false;" unconditionally.
	void TryClearAppliedEffect()
	{
		if (GetColorEffectController().Clear())
		{
			s_hasApplied = false;
		}
		// else: leave s_hasApplied = true - the next Recompute()/Watchdog
		// tick (every frame or every 50ms) will see it's still "applied" and
		// retry the clear instead of silently giving up.
	}

	void ApplyThrottled(const MAGCOLOREFFECT& aEffect, bool aForce = false)
	{
		if (!s_deferredInitDone.load())
			return;

		// Also retry (don't skip) whenever the OS is currently believed to be
		// blocking us - g_DwmLastCallSuccessful only ever gets a fresh answer
		// from an actual Apply() call, and this skip-if-unchanged check used
		// to be the reason a single rejected call could leave the "OS
		// BLOCKED" banner stuck forever even after the OS started accepting
		// calls again: same matrix every frame -> skip forever -> Apply()
		// never gets called again to notice the recovery.
		if (!aForce && s_hasApplied && g_DwmLastCallSuccessful && RoughlyEqual(aEffect, s_lastAppliedEffect))
			return; // Identical and already confirmed applied, save DWM IPC call

		auto now = std::chrono::steady_clock::now();
		auto elapsedMs = std::chrono::duration_cast<std::chrono::milliseconds>(now - s_lastApply).count();
		if (!aForce && elapsedMs < 16) // ~60 Hz DWM cap
			return;

		GetColorEffectController().Apply(aEffect);
		s_lastApply = now;
		s_lastAppliedEffect = aEffect;
		s_hasApplied = true;
	}
}

bool g_DwmLastCallSuccessful = true;

namespace cba
{
	void EnsureDeferredInitialized()
	{
		if (s_deferredInitDone.load()) return;

		// Retry-with-cooldown, not give-up-forever. Regression note: an earlier
		// revision (chasing a "filter dead" bug by diffing against v1.0.2-pre)
		// changed this to mark deferred-init done even when MagInitialize() fails,
		// matching the old code but permanently killing the filter on any transient
		// early failure (GW2/ArcDPS/NVIDIA overlay swapchain setup can still be in
		// flight this early per AGENTS.md section 3). Retrying (throttled, so this can't
		// spam MagInitialize()/the log every frame) is the correct fix - see
		// CLAUDE.md for the fuller story.
		static auto s_lastAttempt = std::chrono::steady_clock::time_point{};
		static bool s_everAttempted = false;
		auto now = std::chrono::steady_clock::now();
		if (s_everAttempted && std::chrono::duration_cast<std::chrono::milliseconds>(now - s_lastAttempt).count() < 1000)
			return;
		s_everAttempted = true;
		s_lastAttempt = now;

		if (GetColorEffectController().Initialize())
		{
			s_deferredInitDone.store(true);
			if (CurrentSettings.Enabled)
			{
				Recompute(/*aForce=*/true);
			}
		}
		else
		{
			// Log only the first failure - a persistent failure retries silently
			// every ~1s afterward, no need to spam the Nexus log for the whole session.
			static bool s_hasLoggedFailure = false;
			if (!s_hasLoggedFailure && APIDefs && APIDefs->Log)
			{
				s_hasLoggedFailure = true;
				APIDefs->Log(ELogLevel_WARNING, "cba4gw2", "MagInitialize deferred init failed - will keep retrying.");
			}
		}
	}

	// ═══════════════════════════════════════════════════════════════════════
	// LAYER 2 of 2: Tag/target highlighting (localized overlay, pre-DWM pixels)
	// ═══════════════════════════════════════════════════════════════════════
	// See Recompute() below for Layer 1 (base screen-wide correction) - the
	// two are independent systems, not alternatives to each other. Full
	// writeup: CLAUDE.md, "How filtering actually composes".
	//
	// This layer merges Commander Tag Enhancer's auto-derived 9 reference-tag
	// colors and every enabled Filter Lab instance into one shared
	// target-color list, handed to HybridScanner. ("Free Filter" used to be
	// a third source here - removed entirely, see CLAUDE.md; this comment
	// still claimed it existed until the 2026-09-09 codebase review caught
	// it, a project-wide grep for "FreeFilter" returns zero matches.)
	// The scanner reads the game's OWN pre-DWM render buffer (via DXGI) and
	// draws small alpha-blended replacement markers over matching pixels -
	// not a full-screen effect, and it does NOT touch the Magnification API.
	// These two sources already run in parallel today (no mutual exclusion
	// at this level - Filter Lab has a one-shot exclusivity trigger against
	// Auto Com-Tag at the UI layer instead, see FilterLab.cpp).
	void UpdateTagEnhancerConflicts()
	{
		static bool s_lastActive = false;
		static float s_lastTolerance = -1.0f;
		static std::vector<TargetColor> s_lastTargets;

		bool anyActive = (CurrentSettings.CommanderTagMode != 0) || CurrentSettings.LabModeEnabled;
		if (!anyActive)
		{
			if (s_lastActive)
			{
				GetHybridScanner().SetHighlighterParams(false, {}, CurrentSettings.EnhancerTolerance);
				s_lastActive = false;
				s_lastTargets.clear();
			}
			for (auto& st : s_tagConflictStates) st = {};
			return;
		}

		std::vector<TargetColor> targetColors;
		targetColors.reserve(10);

		// Filter Layer Matrix (2026-09-11, core/FilterLayers.h) - the
		// sequential position in GetFilterLayerOrder()'s sorted list becomes
		// each target's match-priority rank (0 = wins first). Computed once
		// here rather than read live per-target so every target from the
		// same layer gets the exact same rank even if GetFilterLayerOrder()
		// re-sorts between calls.
		std::vector<FilterLayerInfo> layerOrder = GetFilterLayerOrder();
		auto layerRankOf = [&](int aLayerId) -> int {
			for (size_t i = 0; i < layerOrder.size(); ++i)
				if (layerOrder[i].id == aLayerId) return (int)i;
			return (int)layerOrder.size(); // not in the list (e.g. layer disabled) - lowest priority
		};

		if (CurrentSettings.CommanderTagMode != 0)
		{
			BalanceType defType = CurrentSettings.Mixed 
				? (CurrentSettings.MixedBySeverity01 > CurrentSettings.MixedRgSeverity01 ? BalanceType::Tritan : BalanceType::Deutan)
				: CurrentSettings.Type;
			double sev = CurrentSettings.Mixed 
				? (CurrentSettings.MixedRgSeverity01 > CurrentSettings.MixedBySeverity01 ? CurrentSettings.MixedRgSeverity01 : CurrentSettings.MixedBySeverity01)
				: CurrentSettings.Severity01;

			struct SimTag {
				float origR, origG, origB;
				float simR, simG, simB;
				float luma;
			};
			// Full-pipeline perception model (2026-09-11). What a user actually
			// SEES for a colour sitting in the pre-DWM framebuffer is
			// Sim(M x colour), not Sim(colour): the DWM correction matrix M is
			// applied to everything on screen, the scanner's own overlay
			// markers included (see "How filtering actually composes" in
			// CLAUDE.md). This enhancer used to evaluate Sim(colour) - i.e. it
			// optimised for a pipeline stage that never exists in isolation,
			// which is the long-standing "Auto Com-Tag + base correction looks
			// off together" item. Both sides of every comparison below now run
			// through the same model, so conflicts and replacements are judged
			// on what reaches the eye. Derivation: COLOR_MATH.md section 8.
			//
			// M is identity while the master filter is off, so this is an
			// exact no-op in that state, not a behaviour change.
			double dispM[3][3];
			EffectiveDisplayMatrix(dispM);

			auto perceived = [&](float aR, float aG, float aB,
			                     float& aOutR, float& aOutG, float& aOutB)
			{
				double dr = 0.0, dg = 0.0, db = 0.0;
				ColorMatrix::ApplyPixel(aR, aG, aB, dispM, dr, dg, db);   // what the monitor emits
				double sr = 0.0, sg = 0.0, sb = 0.0;
				ColorMatrix::SimulatePixel(dr, dg, db, defType, sr, sg, sb); // what the eye reconstructs
				aOutR = (float)(dr + sev * (sr - dr));                    // severity interpolation
				aOutG = (float)(dg + sev * (sg - dg));
				aOutB = (float)(db + sev * (sb - db));
			};

			std::array<SimTag, 9> simTags{};
			for (int i = 0; i < 9; ++i)
			{
				simTags[i].origR = kGw2TagRefs[i].r;
				simTags[i].origG = kGw2TagRefs[i].g;
				simTags[i].origB = kGw2TagRefs[i].b;
				// Luma stays measured on the SOURCE colour: it feeds the
				// "don't return something much darker than the tag was"
				// readability floor further down, which compares two
				// pre-DWM values against each other.
				simTags[i].luma = RelativeLuma(kGw2TagRefs[i].r, kGw2TagRefs[i].g, kGw2TagRefs[i].b);

				perceived(simTags[i].origR, simTags[i].origG, simTags[i].origB,
				          simTags[i].simR, simTags[i].simG, simTags[i].simB);
			}

			// Real, severity-aware conflict detection (2026-09-11 - fixed the
			// "Auto Com-Tag isn't selective anymore" report). This used to
			// branch: SmartEnhancer=true took a STATIC per-CVD-type table
			// (same 5-of-9 "in conflict" indices no matter what Severity
			// was set to - a Severity=0.05 and a Severity=1.0 profile
			// flagged identically), while SmartEnhancer=false ran this real
			// simTags-distance computation instead - the actually-adaptive
			// logic was live in the code the whole time, just hidden behind
			// a checkbox that defaults ON to the cruder table. Both states
			// now use the same real computation; SmartEnhancerDesc already
			// promises "passt... an das oben gewaehlte Farbprofil an" -
			// Severity is part of that profile and now actually matters.
			std::array<bool, 9> hasConflict{};
			constexpr float kConflictThreshold = 0.16f;
			for (int i = 0; i < 9; ++i)
			{
				for (int j = i + 1; j < 9; ++j)
				{
					float dr = simTags[i].simR - simTags[j].simR;
					float dg = simTags[i].simG - simTags[j].simG;
					float db = simTags[i].simB - simTags[j].simB;
					float dist = std::sqrt(dr * dr + dg * dg + db * db);
					if (dist < kConflictThreshold)
					{
						hasConflict[i] = true;
						hasConflict[j] = true;
					}
				}
			}

			for (int i = 0; i < 9; ++i)
			{
				s_tagConflictStates[i].inConflict = hasConflict[i];
				if (!hasConflict[i])
				{
					s_tagConflictStates[i].repR = simTags[i].origR;
					s_tagConflictStates[i].repG = simTags[i].origG;
					s_tagConflictStates[i].repB = simTags[i].origB;
					continue;
				}

				float bestR = simTags[i].origR, bestG = simTags[i].origG, bestB = simTags[i].origB;
				float bestScore = -1.0f;

				float h = 0, s = 0, v = 0;
				RgbToHsv(simTags[i].origR, simTags[i].origG, simTags[i].origB, h, s, v);

				for (int step = 1; step <= 23; ++step)
				{
					float testH = std::fmod(h + step * 15.0f, 360.0f);
					float r = 0, g = 0, b = 0;
					HsvToRgb(testH, s, v, r, g, b);

					float newLuma = RelativeLuma(r, g, b);
					float minLuma = simTags[i].luma * 0.85f;
					if (newLuma < minLuma && newLuma > 1e-4f)
					{
						float scale = minLuma / newLuma;
						r = std::clamp(r * scale, 0.0f, 1.0f);
						g = std::clamp(g * scale, 0.0f, 1.0f);
						b = std::clamp(b * scale, 0.0f, 1.0f);
					}

					// Same full-pipeline model as simTags above - the candidate
					// is a colour the scanner would write into the pre-DWM
					// framebuffer, so it gets transformed by M on its way to
					// the eye exactly like the reference tags do.
					float candSimR = 0.0f, candSimG = 0.0f, candSimB = 0.0f;
					perceived(r, g, b, candSimR, candSimG, candSimB);

					float minDist = 999.0f;
					for (int j = 0; j < 9; ++j)
					{
						if (i == j) continue;
						float dr = candSimR - simTags[j].simR;
						float dg = candSimG - simTags[j].simG;
						float db = candSimB - simTags[j].simB;
						float d = std::sqrt(dr * dr + dg * dg + db * db);
						if (d < minDist) minDist = d;
					}

					if (minDist > bestScore)
					{
						bestScore = minDist;
						bestR = r;
						bestG = g;
						bestB = b;
					}
				}

				s_tagConflictStates[i].repR = bestR;
				s_tagConflictStates[i].repG = bestG;
				s_tagConflictStates[i].repB = bestB;

				TargetColor tc;
				tc.r = simTags[i].origR;
				tc.g = simTags[i].origG;
				tc.b = simTags[i].origB;
				tc.repR = (uint8_t)(std::clamp(bestR * 255.0f, 0.0f, 255.0f));
				tc.repG = (uint8_t)(std::clamp(bestG * 255.0f, 0.0f, 255.0f));
				tc.repB = (uint8_t)(std::clamp(bestB * 255.0f, 0.0f, 255.0f));
				tc.layerPriority = layerRankOf(-1);
				targetColors.push_back(tc);
			}
		}
		else
		{
			for (auto& st : s_tagConflictStates) st = {};
		}

		if (CurrentSettings.LabModeEnabled)
		{
			for (size_t fi = 0; fi < CurrentSettings.LabFilters.size(); ++fi)
			{
				const auto& filter = CurrentSettings.LabFilters[fi];
				if (!filter.Enabled) continue;
				TargetColor labTc;
				labTc.r = filter.TargetRgb[0];
				labTc.g = filter.TargetRgb[1];
				labTc.b = filter.TargetRgb[2];
				labTc.repR = (uint8_t)(std::clamp(filter.ReplaceRgb[0] * 255.0f, 0.0f, 255.0f));
				labTc.repG = (uint8_t)(std::clamp(filter.ReplaceRgb[1] * 255.0f, 0.0f, 255.0f));
				labTc.repB = (uint8_t)(std::clamp(filter.ReplaceRgb[2] * 255.0f, 0.0f, 255.0f));
				labTc.tolerance = (filter.ToleranceTones / 255.0f) * 1.732f;
				labTc.diffusion = filter.Diffusion;
				labTc.actionType = filter.ActionType;
				labTc.layerPriority = layerRankOf((int)fi);
				targetColors.push_back(labTc);
			}
		}

		// Every target above now carries its own tolerance (LabFilters set
		// theirs explicitly); this is only the fallback for Commander-Tag-
		// Enhancer's 9 auto-generated reference targets, which don't set
		// target.tolerance individually - so it's always EnhancerTolerance,
		// independent of whether Filter Lab happens to be active too.
		float effectiveTol = CurrentSettings.EnhancerTolerance;

		bool paramsChanged = (!s_lastActive) || (effectiveTol != s_lastTolerance) || (targetColors.size() != s_lastTargets.size());
		if (!paramsChanged)
		{
			for (size_t k = 0; k < targetColors.size(); ++k)
			{
				if (targetColors[k].r != s_lastTargets[k].r || targetColors[k].g != s_lastTargets[k].g || targetColors[k].b != s_lastTargets[k].b ||
					targetColors[k].repR != s_lastTargets[k].repR || targetColors[k].repG != s_lastTargets[k].repG || targetColors[k].repB != s_lastTargets[k].repB)
				{
					paramsChanged = true;
					break;
				}
			}
		}

		if (paramsChanged)
		{
			s_lastActive = true;
			s_lastTolerance = effectiveTol;
			s_lastTargets = targetColors;
			GetHybridScanner().SetHighlighterParams(true, targetColors, effectiveTol);
		}
	}

	void ResetFilterSettingsAndDisable()
	{
		CurrentSettings.Enabled = false;
		CurrentSettings.Severity01 = 0.0;
		CurrentSettings.Mixed = false;
		CurrentSettings.MixedRgSeverity01 = 0.0;
		CurrentSettings.MixedBySeverity01 = 0.0;
		CurrentSettings.GammaGain = 1.0f;
		CurrentSettings.AutoBrightness = false;

		// If the scanner's worker thread died (see HybridScanner::WorkerThread's
		// comment), this is the explicit "revive everything" the Reset button
		// promises - don't wait for the Watchdog's next 50ms tick to notice.
		// Kept explicit here rather than folded into a module's reset - this
		// is thread-health recovery, not a "back to neutral" settings concern.
		if (!GetHybridScanner().IsRunning()) GetHybridScanner().Initialize();

		// Every optional feature module resets itself (2026-09-09,
		// FeatureModuleRegistry - see core/FeatureModule.h) - this used to be
		// one hand-written line per feature here (CommanderTagMode,
		// EyeComfortModeEnabled+3 sliders, EnableHybridMode, LabModeEnabled),
		// which is exactly the kind of per-feature wiring tax that made this
		// function easy to forget updating for a new module.
		for (const auto& module : FeatureModuleRegistry::Get().GetAll())
			if (module.resetToNeutral) module.resetToNeutral();

		CurrentSettings.Save(AddonDir);
		{
			std::lock_guard<std::mutex> lock(s_recomputeMutex);
			TryClearAppliedEffect();
		}
		// UpdateTagEnhancerConflicts() used to be called here unprotected by
		// s_recomputeMutex, racing the Watchdog thread's own Recompute() call
		// on the same non-atomic state (s_lastTargets, s_tagConflictStates) -
		// same bug shape as the WM_ACTIVATE/HybridScanner races fixed earlier
		// this session (2026-09-10 pre-release review). Removed rather than
		// lock-wrapped: Recompute() below already calls it once, under the
		// lock, immediately after - the standalone call was redundant, not
		// just unsafe.
		Recompute(/*aForce=*/true);
	}

	void ActivateCommanderTagProfile(BalanceType aType)
	{
		EnsureDeferredInitialized();
		CurrentSettings.Enabled = true;
		CurrentSettings.CommanderTagMode = 1;
		CurrentSettings.Type = aType;
		CurrentSettings.Mixed = false;
		// Always jump Strength to 100% - this is a one-click preset button, so
		// its result must be predictable regardless of whatever Strength was
		// set to before. A conditional threshold here (previously: only if
		// below 20%) meant the same button click changed behavior depending
		// on invisible prior state - exactly the kind of inconsistency the
		// Strength slider must not have.
		CurrentSettings.Severity01 = 1.0f;
		// Same redundant-and-unprotected UpdateTagEnhancerConflicts() call
		// removed as in ResetFilterSettingsAndDisable() above - Recompute()
		// below already calls it once, under s_recomputeMutex.
		Recompute(/*aForce=*/true);
	}

	void ToggleMasterEnabled()
	{
		EnsureDeferredInitialized();
		CurrentSettings.Enabled = !CurrentSettings.Enabled;
		CurrentSettings.Save(AddonDir);
		Recompute(/*aForce=*/true);
		UpdateQuickAccessIcon();
	}

	void SetGammaGainManual(float aGain)
	{
		ParameterRegistry::Get().SetFloat(ParamId::GammaGain, aGain);
		CurrentSettings.AutoBrightness = false;
	}

	void ApplyAutoBrightnessGain()
	{
		// Routed through the registry (2026-09-09 codebase review) - was a
		// direct field write bypassing ParameterRegistry::SetFloat, the only
		// two GammaGain writers left that did.
		ParameterRegistry::Get().SetFloat(ParamId::GammaGain, GetBrightnessRetention().recommendedGain);
	}

	void SyncAutoBrightnessGain(bool& aChanged, bool& aSaveNeeded)
	{
		if (!CurrentSettings.AutoBrightness) return;
		BrightnessRetentionResult retention = GetBrightnessRetention();
		if (std::abs(CurrentSettings.GammaGain - retention.recommendedGain) > 0.005f)
		{
			ParameterRegistry::Get().SetFloat(ParamId::GammaGain, retention.recommendedGain);
			aChanged = true;
			aSaveNeeded = true;
		}
	}

	void ResetUiLayout()
	{
		s_resetMainWindowPos = true;
		s_resetGraphWindowPos = true;
		s_resetLabWindowPos = true;
		s_resetVisionLabWindowPos = true;
		CurrentSettings.ToolbarIconPosX = 405.0f;
		CurrentSettings.ToolbarIconPosY = 8.0f;
	}

	BrightnessRetentionResult GetBrightnessRetention()
	{
		static const struct { float r, g, b; } kAmbientColors[5] = {
			{ 0.45f, 0.32f, 0.20f }, // Erdbraun
			{ 0.22f, 0.48f, 0.20f }, // Laub
			{ 0.35f, 0.60f, 0.85f }, // Himmel
			{ 0.52f, 0.52f, 0.52f }, // Stein
			{ 0.95f, 0.90f, 0.70f }  // Sonnenlicht
		};

		// Measures the whole COLOUR stack, not just the CVD correction
		// (2026-09-11, Emi: "die Helligkeitsregelung orientiert sich am
		// Filter-Setting, ist aber noch nicht vollstaendig in der Logik").
		// Eye-Sensitive Mode genuinely costs luminance - a blue filter and a
		// desaturation both darken the picture - but this measurement used to
		// see only the CVD matrix, so Auto-Brightness under-compensated
		// whenever Eye-Sensitive Mode was turned up. ColorStackMatrix()
		// deliberately excludes GammaGain, which is the very value being
		// solved for here: including it would close a feedback loop.
		// No-op while Eye-Sensitive Mode is off (its matrix is identity then).
		double m3x3[3][3];
		ColorStackMatrix(m3x3);

		float sumOrig = 0.0f;
		float sumTrans = 0.0f;

		auto processColor = [&](float r, float g, float b) {
			float origLuma = RelativeLuma(r, g, b);
			sumOrig += origLuma;

			float trR = (float)(m3x3[0][0] * r + m3x3[0][1] * g + m3x3[0][2] * b);
			float trG = (float)(m3x3[1][0] * r + m3x3[1][1] * g + m3x3[1][2] * b);
			float trB = (float)(m3x3[2][0] * r + m3x3[2][1] * g + m3x3[2][2] * b);

			trR = std::clamp(trR, 0.0f, 1.0f);
			trG = std::clamp(trG, 0.0f, 1.0f);
			trB = std::clamp(trB, 0.0f, 1.0f);

			float transLuma = RelativeLuma(trR, trG, trB);
			sumTrans += transLuma;
		};

		// NOTE: 8, not 9 - kGw2TagRefs[8] is White, and it is skipped. Flagged
		// 2026-09-11 as genuinely ambiguous rather than silently "fixed",
		// because it reads exactly like an off-by-one against a [9] array but
		// has a defensible reading too: white is invariant under the
		// correction (see COLOR_MATH.md's white-point proof), so including it
		// would add an identical value to both sums and drag the retention
		// ratio toward 1.0 - and neutrals are already represented in the
		// ambient sample below by "Stein" (0.52 grey). Including it would
		// lower the recommended gain, i.e. visibly change everyone's
		// brightness, so it is Emi's call to make, not a silent edit.
		for (int i = 0; i < 8; ++i)
		{
			processColor(kGw2TagRefs[i].r, kGw2TagRefs[i].g, kGw2TagRefs[i].b);
		}
		for (int i = 0; i < 5; ++i)
		{
			processColor(kAmbientColors[i].r, kAmbientColors[i].g, kAmbientColors[i].b);
		}

		BrightnessRetentionResult res{};
		if (sumOrig > 1e-4f)
		{
			res.retentionRatio = sumTrans / sumOrig;
		}
		else
		{
			res.retentionRatio = 1.0f;
		}

		float inv = (res.retentionRatio > 1e-4f) ? (1.0f / res.retentionRatio) : 1.0f;
		// Read the clamp from ParameterRegistry's GammaGain metadata instead
		// of a hardcoded 0.70/1.30 literal - this was the third independent
		// copy of that range in the codebase (found in the 2026-09-09
		// codebase review), one clamp source now instead of three that can
		// drift apart.
		const ParamMeta& gammaMeta = ParameterRegistry::Get().GetMeta(ParamId::GammaGain);
		res.recommendedGain = std::clamp(inv, gammaMeta.minF, gammaMeta.maxF);
		return res;
	}

	// ═══════════════════════════════════════════════════════════════════════
	// LAYER 1 of 2: Base screen-wide correction (DWM Magnification effect)
	// ═══════════════════════════════════════════════════════════════════════
	// See UpdateTagEnhancerConflicts() above for Layer 2 (tag/target
	// highlighting) - the two are independent systems, not alternatives.
	//
	// Builds a 3x3 matrix purely from Type/Severity01/Mixed (+ GammaGain
	// scaling), converts it, and calls MagSetFullscreenColorEffect - this is
	// the ONLY thing that touches the Magnification API. Affects literally
	// everything on screen (game, ImGui, cursor, Layer 2's own overlay too),
	// independent of CommanderTagMode/LabModeEnabled
	// entirely - enabling/disabling those never touches this matrix.
	void Recompute(bool aForce)
	{
		std::lock_guard<std::mutex> lock(s_recomputeMutex);

		if (!s_deferredInitDone.load())
		{
			return;
		}

		UpdateTagEnhancerConflicts();

		static bool s_lastKnownQaActive = false;
		static bool s_qaInitDone = false;
		if (!s_qaInitDone || s_lastKnownQaActive != CurrentSettings.Enabled)
		{
			s_lastKnownQaActive = CurrentSettings.Enabled;
			s_qaInitDone = true;
			UpdateQuickAccessIcon();
		}

		// Compare-hold suspends the DWM stage exactly like Enabled=false does,
		// but without touching Enabled itself - the UI must keep showing "ON"
		// while the user peeks at the raw image, otherwise the comparison
		// would also flip every status readout it is meant to validate.
		if (!CurrentSettings.Enabled || s_compareHoldActive.load())
		{
			if (s_hasApplied)
			{
				TryClearAppliedEffect();
			}
			return;
		}

		HWND fg = GetForegroundWindow();
		DWORD fgPid = 0;
		if (fg) GetWindowThreadProcessId(fg, &fgPid);
		bool isGw2Foreground = (fg && fgPid == GetCurrentProcessId());
		bool isMinimized = s_gw2Minimized.load() || (s_gw2Hwnd.load() && IsIconic(s_gw2Hwnd.load()));

		bool shouldBeActive = (!isMinimized && (isGw2Foreground || CurrentSettings.SystemWide));

		if (!shouldBeActive)
		{
			if (s_hasApplied)
			{
				TryClearAppliedEffect();
			}
			return;
		}

		// The whole composition (CVD correction, then Eye-Sensitive Mode on
		// top of it, then GammaGain) lives in EffectiveDisplayMatrix()
		// (core/FilterLayers.cpp) as of 2026-09-11 - it used to be spelled
		// out here, which meant the tag enhancer had no way to ask "what is
		// actually being applied to the screen right now" and silently
		// modelled a pipeline without this stage at all. Reaching this line
		// already implies Enabled == true, so the function's !Enabled
		// identity branch is not in play here.
		double m3x3[3][3];
		EffectiveDisplayMatrix(m3x3);

		MAGCOLOREFFECT effect = ColorMatrix::ToMagColorEffect(m3x3);
		ApplyThrottled(effect, aForce);
	}

	namespace
	{
		void WatchdogLoop()
		{
			while (s_watchdogRunning)
			{
				std::this_thread::sleep_for(std::chrono::milliseconds(50));

				// Per-iteration try/catch (2026-09-09, same fix and same
				// reasoning as HybridScanner::WorkerThread - see its comment):
				// this loop carries the stuck-effect recovery, foreground/
				// minimize tracking, and the HybridScanner self-heal below.
				// An unguarded exception anywhere here would silently end
				// the Watchdog thread for the rest of the process - the one
				// thread whose entire job is being a safety net, gone with
				// no way to notice or recover short of restarting GW2.
				try
				{
					if (!s_deferredInitDone.load())
					{
						continue;
					}

					// Release-edge safety net for hold-to-compare: if GW2 loses
					// focus while the key is physically down, Nexus never
					// delivers the release, and the flag would keep the filter
					// suppressed indefinitely - looking exactly like "the addon
					// broke", with no recovery short of pressing and releasing
					// the bind again. Same stuck-state class as the two
					// effect/thread bugs already fixed here, so it gets the
					// same treatment: the safety net clears it.
					if (s_compareHoldActive.load() && !s_gw2Minimized.load())
					{
						HWND fgw = GetForegroundWindow();
						DWORD fgpid = 0;
						if (fgw) GetWindowThreadProcessId(fgw, &fgpid);
						if (!fgw || fgpid != GetCurrentProcessId())
						{
							s_compareHoldActive.store(false);
						}
					}

					// Self-heal the HybridScanner's background worker thread
					// if it ever died (see HybridScanner::WorkerThread's
					// comment) while a feature that needs it is still active -
					// without this, a killed thread stayed dead for the rest
					// of the process even after toggling Enabled off/on.
					if ((CurrentSettings.CommanderTagMode != 0 || CurrentSettings.LabModeEnabled || CurrentSettings.EnableHybridMode)
						&& !GetHybridScanner().IsRunning())
					{
						GetHybridScanner().Initialize();
					}

					if (!CurrentSettings.Enabled)
					{
						if (s_hasApplied)
						{
							std::lock_guard<std::mutex> lock(s_recomputeMutex);
							TryClearAppliedEffect();
						}
						continue;
					}

					HWND fg = GetForegroundWindow();
					DWORD fgPid = 0;
					if (fg) GetWindowThreadProcessId(fg, &fgPid);
					bool isGw2Foreground = (fg && fgPid == GetCurrentProcessId());
					bool isMinimized = s_gw2Minimized.load() || (s_gw2Hwnd.load() && IsIconic(s_gw2Hwnd.load()));

					bool shouldBeActive = (!isMinimized && (isGw2Foreground || CurrentSettings.SystemWide));

					if (!shouldBeActive)
					{
						if (s_hasApplied)
						{
							std::lock_guard<std::mutex> lock(s_recomputeMutex);
							TryClearAppliedEffect();
						}
					}
					else
					{
						if (!s_hasApplied)
						{
							Recompute(/*aForce=*/true);
						}
					}
				}
				catch (...)
				{
					// Swallow and keep looping - a single bad tick must not
					// end the safety-net thread. Nothing to log to here (no
					// Nexus logging API wired up), the point is survival.
				}
			}
		}
	}

	UINT AddonWndProc(HWND aWnd, UINT aMsg, WPARAM aWParam, LPARAM aLParam)
	{
		if (aWnd) s_gw2Hwnd = aWnd;
		switch (aMsg)
		{
			case WM_ACTIVATE:
			{
				WORD state = LOWORD(aWParam);
				if (state == WA_INACTIVE)
				{
					if (!CurrentSettings.SystemWide)
					{
						// Every other mutator of s_hasApplied/s_lastAppliedEffect
						// (Recompute, WatchdogLoop) takes s_recomputeMutex - this
						// call site didn't, so the WndProc message thread could
						// genuinely race the Watchdog thread over the same plain
						// shared state (found in the 2026-09-09 codebase review,
						// same bug shape as the HybridScanner thread-death fix).
						std::lock_guard<std::mutex> lock(s_recomputeMutex);
						TryClearAppliedEffect();
					}
				}
				else
				{
					s_gw2Minimized = false;
					Recompute(/*aForce=*/true);
				}
				break;
			}
			case WM_SIZE:
			{
				if (aWParam == SIZE_MINIMIZED)
				{
					s_gw2Minimized = true;
					std::lock_guard<std::mutex> lock(s_recomputeMutex);
					TryClearAppliedEffect();
				}
				else if (aWParam == SIZE_RESTORED || aWParam == SIZE_MAXIMIZED)
				{
					s_gw2Minimized = false;
					Recompute(/*aForce=*/true);
				}
				break;
			}
			// WM_KEYDOWN/WM_SYSKEYDOWN handling for Filter-Off/Main-Window/Sensor-Graph
			// used to live here as a second, hardcoded-combo input path, running
			// in parallel with Nexus's InputBinds -> ProcessKeybind() below (which
			// is user-rebindable via Nexus's own keybind UI - see AddonLoad's
			// InputBinds.RegisterWithString calls). Both paths fired on the same
			// default keypress, double-toggling ShowGraphWindow etc. back to its
			// starting value - the likely cause of "Sensor Graph HUD keybind does
			// nothing" (CLAUDE.md loose end). Removed rather than deduplicated:
			// ProcessKeybind() already covers all three actions correctly.
		}
		return aMsg;
	}

	void ProcessKeybind(const char* aIdentifier, bool aIsRelease)
	{
		// Hold-to-compare is the one bind that cares about the release edge -
		// handled before the early-return below, which every other (toggle-
		// style) bind relies on. See PRODUCT_CONCEPT.md 3.2: a toggle costs
		// two presses and the moment; holding answers "is this doing
		// anything?" against the live game in half a second.
		if (strcmp(aIdentifier, "CBA - Compare (hold)") == 0 || strcmp(aIdentifier, "KB_CBA_COMPARE") == 0)
		{
			s_compareHoldActive.store(!aIsRelease);
			Recompute(/*aForce=*/true);
			return;
		}

		if (aIsRelease) return;

		if (strcmp(aIdentifier, "CBA - Filter Off") == 0 || strcmp(aIdentifier, "CBA - Not-Aus") == 0 || strcmp(aIdentifier, "KB_CBA_PANIC") == 0)
		{
			// Full reset (base correction + Commander Tag Enhancer + Hybrid Mode +
			// Free Filter + Filter Lab), not just Enabled=false - this used to only
			// touch Enabled, so Commander Tag Enhancer's tag-highlight overlay kept
			// running after "Filter Off", which looked like the filter was still on.
			ResetFilterSettingsAndDisable();
		}
		else if (strcmp(aIdentifier, "CBA - Main Window") == 0 || strcmp(aIdentifier, "KB_CBA_WINDOW") == 0)
		{
			// Advanced Mode gate (2026-09-09) - only blocks opening. If the
			// window is somehow already open (e.g. from before the gate
			// existed), the keybind can still close it; nothing traps a
			// window open forever.
			if (!CurrentSettings.AdvancedModeUnlocked && !CurrentSettings.ShowMainWindow) return;
			EnsureDeferredInitialized();
			CurrentSettings.ShowMainWindow = !CurrentSettings.ShowMainWindow;
			if (CurrentSettings.ShowMainWindow) s_focusMainWindow = true;
		}
		else if (strcmp(aIdentifier, "CBA - Sensor Graph") == 0 || strcmp(aIdentifier, "KB_CBA_GRAPH") == 0)
		{
			if (!CurrentSettings.AdvancedModeUnlocked && !CurrentSettings.ShowGraphWindow) return;
			EnsureDeferredInitialized();
			CurrentSettings.ShowGraphWindow = !CurrentSettings.ShowGraphWindow;
			if (CurrentSettings.ShowGraphWindow) s_focusGraphWindow = true;
		}
	}

	void UpdateQuickAccessIcon()
	{
		if (!APIDefs) return;

		// If movable toolbar icon is active, remove stationary shortcut from Nexus
		// so there is never a duplicate stationary icon!
		if (CurrentSettings.ShowQuickAccessIcon && CurrentSettings.MovableToolbarIcon)
		{
			if (APIDefs->QuickAccess.Remove)
			{
				APIDefs->QuickAccess.Remove("QA_CBA");
			}
			return;
		}

		if (CurrentSettings.ShowQuickAccessIcon)
		{
			// Was fragile: inspected the FIRST LETTER of an already-resolved string to
			// infer which language block Strings() picked - cba::IsGerman() (L10n.h)
			// already does the real check directly and had zero callers until now
			// (found in the 2026-09-09 codebase review).
			bool isDe = cba::IsGerman();
			bool isActive = CurrentSettings.Enabled;
			const char* texNormal = isActive ? "CBA_ICON" : "CBA_ICON_INACTIVE";
			// Hover always brightens to the same near-white tone regardless
			// of Active/Inactive (2026-09-10, "volle Integration in die
			// Nexus Icon Familie") - matches every native Nexus icon, which
			// brightens on hover the same way no matter its own state.
			// Nexus.h itself only supports 2 textures per icon (Normal/
			// Hover), so the family-hover tone lives in texHover and CBA's
			// own on/off distinction lives entirely in texNormal.
			const char* texHover = "CBA_ICON_HOVER";
			const char* tooltip   = isDe
				? (isActive ? "cba4gw2 [Aktiv] (Strg+Shift+C / Filter Aus: Strg+Shift+O)"
				            : "cba4gw2 [Inaktiv] (Strg+Shift+C / Filter Ein: Strg+Shift+C)")
				: (isActive ? "cba4gw2 [Active] (Ctrl+Shift+C / Filter Off: Ctrl+Shift+O)"
				            : "cba4gw2 [Inactive] (Ctrl+Shift+C / Filter On: Ctrl+Shift+C)");

			if (APIDefs->QuickAccess.Add)
			{
				APIDefs->QuickAccess.Add("QA_CBA", texNormal, texHover, "CBA - Main Window", tooltip);
			}
		}
		else
		{
			if (APIDefs->QuickAccess.Remove)
			{
				APIDefs->QuickAccess.Remove("QA_CBA");
			}
		}
	}

	void AddonOptions()
	{
		if (!ImGui::GetCurrentContext()) return;
		EnsureDeferredInitialized();
		RenderEmbeddedOptions();
	}

	void AddonRenderWindow()
	{
		auto tStartTotal = std::chrono::high_resolution_clock::now();

		// Safe Start Dialog Gate
		if (s_safeStartPending.load() && ImGui::GetCurrentContext())
		{
			auto t0 = std::chrono::high_resolution_clock::now();
			RenderSafeStartDialog();
			auto t1 = std::chrono::high_resolution_clock::now();
			g_perfSafeStartMs = std::chrono::duration<double, std::milli>(t1 - t0).count();
		}
		else
		{
			g_perfSafeStartMs = 0.0;
		}

		// ── Deferred Warmup Gate ────────────────────────────────────────────────
		// Wait 30 frames for stable GW2/D3D11/ArcDPS/NVIDIA initialization before DWM
		// Prevents crashes during game startup (per AGENTS.md rule)
		if (!s_deferredInitDone.load())
		{
			static int s_renderWarmupFrames = 0;
			if (++s_renderWarmupFrames >= 30)
			{
				EnsureDeferredInitialized();
			}
		}

		// ── Hybrid Scanner Frame Capture & Overlay ──────────────────────────────
		if ((CurrentSettings.EnableHybridMode || CurrentSettings.CommanderTagMode != 0) && s_deferredInitDone.load())
		{
			IDXGISwapChain* swapChain = APIDefs ? static_cast<IDXGISwapChain*>(APIDefs->SwapChain) : nullptr;
			if (swapChain)
			{
				GetHybridScanner().ScanFrame(swapChain);
			}

			// Suppress the tag/target overlay too while compare-hold is down -
			// otherwise the "unfiltered" reference would still carry stage 2,
			// and the comparison would only prove half the pipeline.
			int texW = 0, texH = 0;
			ID3D11ShaderResourceView* srv = GetHybridScanner().GetOverlaySRV(texW, texH);
			if (srv && !s_compareHoldActive.load())
			{
				ImVec2 disp = ImGui::GetIO().DisplaySize;
				ImGui::GetBackgroundDrawList()->AddImage((ImTextureID)srv, ImVec2(0, 0), disp);
			}
		}

		if (s_showC64Credits.load())
		{
			RenderC64CreditsOverlay();
		}

		// ── Movable Toolbar Icon (Shift + LMB Drag) ──────────────────────────
		RenderMovableToolbarIcon();

		// ── Window 1: CBA Main Window ─────────────────────────────────────────
		if (CurrentSettings.ShowMainWindow && ImGui::GetCurrentContext())
		{
			auto t0 = std::chrono::high_resolution_clock::now();

			if (s_focusMainWindow)
			{
				ImGui::SetNextWindowFocus();
				s_focusMainWindow = false;
			}

			ImVec2 disp = ImGui::GetIO().DisplaySize;
			float screenH = (disp.y > 400.0f) ? disp.y : 1080.0f;
			float defaultW = 530.0f;
			float defaultH = std::clamp(screenH * 0.76f, 620.0f, 860.0f);

			ImGui::SetNextWindowBgAlpha(0.96f);
			ImGui::PushStyleColor(ImGuiCol_WindowBg,             ImVec4(0.06f, 0.08f, 0.12f, 0.96f));
			ImGui::PushStyleColor(ImGuiCol_ScrollbarBg,          ImVec4(0.04f, 0.06f, 0.09f, 0.65f));
			ImGui::PushStyleColor(ImGuiCol_ScrollbarGrab,        ImVec4(0.24f, 0.42f, 0.65f, 0.85f));
			ImGui::PushStyleColor(ImGuiCol_ScrollbarGrabHovered, ImVec4(0.34f, 0.56f, 0.85f, 0.95f));
			ImGui::PushStyleColor(ImGuiCol_ScrollbarGrabActive,  ImVec4(0.42f, 0.72f, 1.00f, 1.00f));
			ImGui::PushStyleColor(ImGuiCol_Border,               ImVec4(0.22f, 0.35f, 0.52f, 0.55f));

			ImGui::PushStyleVar(ImGuiStyleVar_ScrollbarSize,     14.0f);
			ImGui::PushStyleVar(ImGuiStyleVar_ScrollbarRounding, 6.0f);
			ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding,     ImVec2(12.0f, 10.0f));

			// Sleek, variable sidebar sizing: min 480x420, max 1600 x screenH
			ImGui::SetNextWindowSizeConstraints(ImVec2(480.0f, 420.0f), ImVec2(1600.0f, screenH - 40.0f));

			if (s_resetMainWindowPos)
			{
				float posX = 40.0f;
				float posY = 60.0f;
				ImGui::SetNextWindowPos(ImVec2(posX, posY), ImGuiCond_Always);
				ImGui::SetNextWindowSize(ImVec2(defaultW, defaultH), ImGuiCond_Always);
				s_resetMainWindowPos = false;
			}
			else
			{
				ImGui::SetNextWindowSize(ImVec2(defaultW, defaultH), ImGuiCond_FirstUseEver);
			}

			// Was fragile: inspected the FIRST LETTER of an already-resolved string to
			// infer which language block Strings() picked - cba::IsGerman() (L10n.h)
			// already does the real check directly and had zero callers until now
			// (found in the 2026-09-09 codebase review).
			bool isDe = cba::IsGerman();
			ImGuiWindowFlags winFlags = ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse;
			if (ImGui::Begin(isDe ? "cba4gw2 - Hauptfenster###CBA_MainWindow" : "cba4gw2 - Main Window###CBA_MainWindow", &CurrentSettings.ShowMainWindow, winFlags))
			{
				RenderMainWindow();
			}
			ImGui::End();
			ImGui::PopStyleVar(3);
			ImGui::PopStyleColor(6);

			auto t1 = std::chrono::high_resolution_clock::now();
			g_perfMainWindowMs = std::chrono::duration<double, std::milli>(t1 - t0).count();
		}
		else
		{
			g_perfMainWindowMs = 0.0;
		}

		// ── Window 2: Sensor & Spectral Graph HUD Window ─────────────────────
		if (CurrentSettings.ShowGraphWindow && ImGui::GetCurrentContext())
		{
			auto t0 = std::chrono::high_resolution_clock::now();

			if (s_focusGraphWindow)
			{
				ImGui::SetNextWindowFocus();
				s_focusGraphWindow = false;
			}

			float clampedOpacity = std::clamp(CurrentSettings.UiOpacity, 0.0f, 1.0f);
			float winBgAlpha = std::clamp(clampedOpacity * 0.96f, 0.05f, 0.96f);
			ImGui::SetNextWindowBgAlpha(winBgAlpha);
			ImGui::PushStyleColor(ImGuiCol_WindowBg, ImVec4(0.04f, 0.06f, 0.10f, winBgAlpha));

			// Sleek, variable HUD sizing: min 340x280, max 1600x1200
			ImGui::SetNextWindowSizeConstraints(ImVec2(340.0f, 280.0f), ImVec2(1600.0f, 1200.0f));

			if (s_resetGraphWindowPos)
			{
				float w = 440.0f;
				float h = 405.0f;
				float posX = 40.0f;
				float posY = 60.0f;
				ImGui::SetNextWindowPos(ImVec2(posX, posY), ImGuiCond_Always);
				ImGui::SetNextWindowSize(ImVec2(w, h), ImGuiCond_Always);
				s_resetGraphWindowPos = false;
			}
			else
			{
				ImGui::SetNextWindowSize(ImVec2(440.0f, 405.0f), ImGuiCond_FirstUseEver);
			}

			ImGuiWindowFlags winFlags = ImGuiWindowFlags_NoCollapse;
			if (ImGui::Begin("cba graph###CBA_GraphWindow", &CurrentSettings.ShowGraphWindow, winFlags))
			{
				RenderGraphWindow();
			}
			ImGui::End();
			ImGui::PopStyleColor();

			auto t1 = std::chrono::high_resolution_clock::now();
			g_perfSensorGraphMs = std::chrono::duration<double, std::milli>(t1 - t0).count();
		}
		else
		{
			g_perfSensorGraphMs = 0.0;
			g_perfCurvesMs = 0.0;
		}

		// ── Window 3: Filter Lab Detached Floating Window ────────────────────
		if (CurrentSettings.ShowLabWindow && ImGui::GetCurrentContext())
		{
			auto t0 = std::chrono::high_resolution_clock::now();

			if (s_focusLabWindow)
			{
				ImGui::SetNextWindowFocus();
				s_focusLabWindow = false;
			}

			ImGui::SetNextWindowBgAlpha(0.96f);
			ImGui::PushStyleColor(ImGuiCol_WindowBg,             ImVec4(0.06f, 0.08f, 0.12f, 0.96f));
			ImGui::PushStyleColor(ImGuiCol_ScrollbarBg,          ImVec4(0.04f, 0.06f, 0.09f, 0.65f));
			ImGui::PushStyleColor(ImGuiCol_ScrollbarGrab,        ImVec4(0.24f, 0.42f, 0.65f, 0.85f));
			ImGui::PushStyleColor(ImGuiCol_ScrollbarGrabHovered, ImVec4(0.34f, 0.56f, 0.85f, 0.95f));
			ImGui::PushStyleColor(ImGuiCol_ScrollbarGrabActive,  ImVec4(0.42f, 0.72f, 1.00f, 1.00f));
			ImGui::PushStyleColor(ImGuiCol_Border,               ImVec4(0.22f, 0.35f, 0.52f, 0.55f));

			ImGui::PushStyleVar(ImGuiStyleVar_ScrollbarSize,     14.0f);
			ImGui::PushStyleVar(ImGuiStyleVar_ScrollbarRounding, 6.0f);
			ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding,     ImVec2(12.0f, 10.0f));

			ImGui::SetNextWindowSizeConstraints(ImVec2(480.0f, 400.0f), ImVec2(1600.0f, 1200.0f));

			if (s_resetLabWindowPos)
			{
				float posX = 40.0f;
				float posY = 60.0f;
				ImGui::SetNextWindowPos(ImVec2(posX, posY), ImGuiCond_Always);
				ImGui::SetNextWindowSize(ImVec2(620.0f, 520.0f), ImGuiCond_Always);
				s_resetLabWindowPos = false;
			}
			else
			{
				ImGui::SetNextWindowSize(ImVec2(620.0f, 520.0f), ImGuiCond_FirstUseEver);
			}

			// Was fragile: inspected the FIRST LETTER of an already-resolved string to
			// infer which language block Strings() picked - cba::IsGerman() (L10n.h)
			// already does the real check directly and had zero callers until now
			// (found in the 2026-09-09 codebase review).
			bool isDe = cba::IsGerman();
			ImGuiWindowFlags winFlags = ImGuiWindowFlags_NoCollapse;
			if (ImGui::Begin(isDe ? "cba4gw2 - Filter-Labor###CBA_LabWindow" : "cba4gw2 - Filter Lab###CBA_LabWindow", &CurrentSettings.ShowLabWindow, winFlags))
			{
				bool labChanged = false;
				bool labSaveNeeded = false;
				DrawFilterLabWidget(isDe, labChanged, labSaveNeeded);
				if (labSaveNeeded)
				{
					CurrentSettings.Save(AddonDir);
					Recompute(/*aForce=*/true);
				}
				else if (labChanged)
				{
					Recompute(/*aForce=*/false);
				}
			}
			ImGui::End();
			ImGui::PopStyleVar(3);
			ImGui::PopStyleColor(6);

			auto t1 = std::chrono::high_resolution_clock::now();
			g_perfFilterLabMs = std::chrono::duration<double, std::milli>(t1 - t0).count();
		}
		else
		{
			g_perfFilterLabMs = 0.0;
		}

		// ── Window 4: Vision Lab Floating Window ─────────────────────────────
		if (CurrentSettings.ShowVisionLabWindow && ImGui::GetCurrentContext())
		{
			auto t0 = std::chrono::high_resolution_clock::now();
			RenderVisionLabWindow();
			auto t1 = std::chrono::high_resolution_clock::now();
			g_perfVisionLabMs = std::chrono::duration<double, std::milli>(t1 - t0).count();
		}
		else
		{
			g_perfVisionLabMs = 0.0;
		}

		auto tEndTotal = std::chrono::high_resolution_clock::now();
		g_perfTotalImGuiMs = std::chrono::duration<double, std::milli>(tEndTotal - tStartTotal).count();
	}

	void AddonLoad(AddonAPI* aApi)
	{
		try
		{
			APIDefs = aApi;
			if (!APIDefs) return;

			if (APIDefs->DataLink.Get)
			{
				NexusLink = (NexusLinkData*)APIDefs->DataLink.Get("DL_NEXUS_LINK");
				MumbleLinkData = (GW2MumbleLink*)APIDefs->DataLink.Get("GW2_MUMBLE_LINK");
			}

			if (APIDefs->ImguiContext)
				ImGui::SetCurrentContext((ImGuiContext*)APIDefs->ImguiContext);
			if (APIDefs->ImguiMalloc && APIDefs->ImguiFree)
				ImGui::SetAllocatorFunctions(
					(void* (*)(size_t, void*))APIDefs->ImguiMalloc,
					(void(*)(void*, void*))APIDefs->ImguiFree);

			const char* dir = (APIDefs->Paths.GetAddonDirectory) ? APIDefs->Paths.GetAddonDirectory("cba") : nullptr;
			AddonDir = dir ? dir : "";
			if (!AddonDir.empty())
			{
				std::error_code ec;
				std::filesystem::create_directories(AddonDir, ec);
			}
			CurrentSettings = Settings::Load(AddonDir);
			RegisterAllParameters();
			RegisterAllFeatureModules();
			Theme::ApplyTheme(CurrentSettings.UiTheme);

			// Auto-Start Profile: the one deliberate exception to "the filter
			// always starts neutral" (Settings::Load forces Enabled=false
			// unconditionally). If Emi has picked a saved profile slot to
			// auto-load, apply it now and turn the filter on - but never on
			// crash recovery, that's exactly the "unexpected color shift on
			// launch" scenario the Safe-Start Gate exists to prevent, and an
			// auto-start profile shouldn't be able to bypass it.
			if (!CurrentSettings.SafeModeTriggered &&
			    CurrentSettings.AutoStartSlot >= 0 && CurrentSettings.AutoStartSlot < 3 &&
			    CurrentSettings.Slots[CurrentSettings.AutoStartSlot].Used)
			{
				const Settings::ProfileSlot& slot = CurrentSettings.Slots[CurrentSettings.AutoStartSlot];
				CurrentSettings.Type = slot.Type;
				CurrentSettings.Severity01 = slot.Severity01;
				CurrentSettings.Mixed = slot.Mixed;
				CurrentSettings.MixedRgSeverity01 = slot.MixedRg01;
				CurrentSettings.MixedBySeverity01 = slot.MixedBy01;
				CurrentSettings.GammaGain = slot.GammaGain;
				CurrentSettings.Enabled = true;
				// Keep the Profile Slot picker's highlight consistent with
				// what's actually loaded - without this, the UI would show
				// Slot 1 highlighted after an auto-started Slot 3, since
				// s_activeSlotIdx otherwise stays at its process-start
				// default (0) until the user clicks a slot chip themselves.
				ParameterRegistry::Get().SetInt(ParamId::ActiveSlotIdx, CurrentSettings.AutoStartSlot);
			}

			// The DetachedWindow backward-compat migration used to live here
			// (open Main Window if an old settings.ini had it set) - removed
			// entirely 2026-09-09 (codebase review): Settings::Load() itself
			// unconditionally forced DetachedWindow=false before this code
			// ever ran, so the migration was permanently unreachable, and it
			// also directly contradicted the newer, deliberate "all windows
			// start closed on every launch" policy a few lines above in
			// Settings::Load() - re-enabling it would fight that policy, not
			// restore a real feature.

			// Initialize hybrid background scanner
			GetHybridScanner().Initialize();
			GetHybridScanner().SetEnabled(CurrentSettings.EnableHybridMode);
			UpdateTagEnhancerConflicts();

			// Session Breadcrumb crash guard: mark session running
			Settings::MarkRunning(AddonDir);

			// Safe-Start Gate: Show warning dialog on crash or first run
			if (CurrentSettings.SafeModeTriggered)
			{
				// Crash detected (lockfile exists): show warning, filter disabled by Settings::Load
				s_safeStartPending.store(true);
			}
			else if (!CurrentSettings.AlwaysDirectStart)
			{
				// First run or user preference: show welcome dialog
				s_safeStartPending.store(true);
			}

			// Escape closes windows
			if (APIDefs->UI.RegisterCloseOnEscape)
			{
				APIDefs->UI.RegisterCloseOnEscape("cba4gw2 - Hauptfenster###CBA_MainWindow", &CurrentSettings.ShowMainWindow);
				APIDefs->UI.RegisterCloseOnEscape("cba4gw2 - Main Window###CBA_MainWindow", &CurrentSettings.ShowMainWindow);
				APIDefs->UI.RegisterCloseOnEscape("cba graph###CBA_GraphWindow", &CurrentSettings.ShowGraphWindow);
				APIDefs->UI.RegisterCloseOnEscape("cba4gw2 - Sensor Graph###CBA_GraphWindow", &CurrentSettings.ShowGraphWindow);
				APIDefs->UI.RegisterCloseOnEscape("cba4gw2 - Filter-Labor###CBA_LabWindow", &CurrentSettings.ShowLabWindow);
				APIDefs->UI.RegisterCloseOnEscape("cba4gw2 - Filter Lab###CBA_LabWindow", &CurrentSettings.ShowLabWindow);
				APIDefs->UI.RegisterCloseOnEscape("cba4gw2 - Vision Lab###CBA_VisionLabWindow", &CurrentSettings.ShowVisionLabWindow);
			}

			// Renderers
			if (APIDefs->Renderer.Register)
			{
				APIDefs->Renderer.Register(ERenderType_OptionsRender, AddonOptions);
				APIDefs->Renderer.Register(ERenderType_Render, AddonRenderWindow);
			}

			// WndProc
			if (APIDefs->WndProc.Register)
			{
				APIDefs->WndProc.Register(AddonWndProc);
			}

			// QuickAccess toolbar icon & window toggle keybinds
			if (APIDefs->InputBinds.RegisterWithString)
			{
				APIDefs->InputBinds.RegisterWithString("CBA - Main Window", ProcessKeybind, "CTRL+SHIFT+C");
				APIDefs->InputBinds.RegisterWithString("CBA - Sensor Graph", ProcessKeybind, "CTRL+SHIFT+G");
				APIDefs->InputBinds.RegisterWithString("CBA - Filter Off", ProcessKeybind, "CTRL+SHIFT+O");
				APIDefs->InputBinds.RegisterWithString("CBA - Compare (hold)", ProcessKeybind, "CTRL+SHIFT+V");
			}
			if (APIDefs->Textures.GetOrCreateFromMemory)
			{
				APIDefs->Textures.GetOrCreateFromMemory("CBA_ICON", (void*)kCbaIconPng, sizeof(kCbaIconPng));
				APIDefs->Textures.GetOrCreateFromMemory("CBA_ICON_INACTIVE", (void*)kCbaIconInactivePng, sizeof(kCbaIconInactivePng));
				APIDefs->Textures.GetOrCreateFromMemory("CBA_ICON_HOVER", (void*)kCbaIconHoverPng, sizeof(kCbaIconHoverPng));
			}
			if (CurrentSettings.ShowQuickAccessIcon)
			{
				UpdateQuickAccessIcon();
			}

			// Start state watchdog thread (monitors focus transitions every 50ms)
			s_watchdogRunning = true;
			s_watchdogThread = std::thread(WatchdogLoop);
		}
		catch (...)
		{
			// Never allow an unhandled exception to escape AddonLoad
		}
	}

	void AddonUnload()
	{
		// Visually-critical cleanup FIRST, in its own try/catch, before anything
		// else in this function gets a chance to throw and have the outer
		// catch(...) swallow it before we ever get here. This used to be the
		// very last thing AddonUnload() did (after ~15 other steps: settings
		// save, watchdog thread join, several Nexus API deregistrations,
		// HybridScanner shutdown) - if any of those failed, the screen-visible
		// fix never ran. See CLAUDE.md 2026-09-09 for the full "filter still
		// active after Off/Disable/Uninstall" investigation - this, the
		// DLL_PROCESS_DETACH fallback in DllMain below, and the Watchdog
		// thread's continuous Enabled-vs-applied check are the three
		// independent layers covering that class of bug now.
		try
		{
			GetColorEffectController().Clear();
			GetColorEffectController().Shutdown();
		}
		catch (...)
		{
		}

		try
		{
			// Session Breadcrumb: mark graceful exit
			Settings::MarkCleanExit(AddonDir);

			// Always close windows on game exit so they start closed on next launch
			CurrentSettings.ShowMainWindow = false;
			CurrentSettings.ShowGraphWindow = false;
			CurrentSettings.ShowLabWindow = false;
			CurrentSettings.ShowVisionLabWindow = false;
			CurrentSettings.Save(AddonDir);

			s_showC64Credits.store(false);
			StopC64Audio();

			// Stop state watchdog thread
			s_watchdogRunning = false;
			if (s_watchdogThread.joinable())
			{
				s_watchdogThread.join();
			}

			if (APIDefs)
			{
				if (APIDefs->QuickAccess.Remove)
				{
					APIDefs->QuickAccess.Remove("QA_CBA");
				}
				if (APIDefs->InputBinds.Deregister)
				{
					APIDefs->InputBinds.Deregister("CBA - Main Window");
					APIDefs->InputBinds.Deregister("CBA - Filter Off");
					APIDefs->InputBinds.Deregister("CBA - Sensor Graph");
					APIDefs->InputBinds.Deregister("CBA - Compare (hold)");
					APIDefs->InputBinds.Deregister("CBA - Not-Aus");
					APIDefs->InputBinds.Deregister("KB_CBA_WINDOW");
				}
				if (APIDefs->UI.DeregisterCloseOnEscape)
				{
					APIDefs->UI.DeregisterCloseOnEscape("cba4gw2 - Hauptfenster###CBA_MainWindow");
					APIDefs->UI.DeregisterCloseOnEscape("cba4gw2 - Main Window###CBA_MainWindow");
					APIDefs->UI.DeregisterCloseOnEscape("cba graph###CBA_GraphWindow");
					APIDefs->UI.DeregisterCloseOnEscape("cba4gw2 - Sensor Graph###CBA_GraphWindow");
					APIDefs->UI.DeregisterCloseOnEscape("cba4gw2 - Filter-Labor###CBA_LabWindow");
					APIDefs->UI.DeregisterCloseOnEscape("cba4gw2 - Filter Lab###CBA_LabWindow");
					APIDefs->UI.DeregisterCloseOnEscape("cba4gw2 - Vision Lab###CBA_VisionLabWindow");
				}
				if (APIDefs->WndProc.Deregister)
					APIDefs->WndProc.Deregister(AddonWndProc);
				if (APIDefs->Renderer.Deregister)
				{
					APIDefs->Renderer.Deregister(AddonRenderWindow);
					APIDefs->Renderer.Deregister(AddonOptions);
				}
			}

			GetHybridScanner().Shutdown();
		}
		catch (...)
		{
		}
	}
}

BOOL APIENTRY DllMain(HMODULE aModule, DWORD aReasonForCall, LPVOID)
{
	if (aReasonForCall == DLL_PROCESS_ATTACH)
	{
		AddonModuleHandle = aModule;
	}
	else if (aReasonForCall == DLL_PROCESS_DETACH)
	{
		// Last-resort safety net: DLL_PROCESS_DETACH fires whenever this DLL
		// leaves the process for ANY reason (normal unload, Nexus addon
		// uninstall, crash unwind) - unlike AddonUnload(), which only runs on
		// the "well-behaved shutdown" path. Emi hit exactly the gap this
		// covers: uninstalling cba via Nexus while GW2 kept running left the
		// DWM fullscreen color effect stuck system-wide, because whatever
		// Nexus's uninstall does apparently doesn't call AddonUnload() first.
		// Shutdown() is a no-op if AddonUnload() already ran (it checks
		// _initialized), so this is safe to call unconditionally here.
		// Never let an exception escape DllMain - that's undefined behavior
		// during DLL unload, possibly worse than the stuck-filter bug this
		// whole block exists to prevent.
		try
		{
			if (cba::GetColorEffectController().IsInitialized())
			{
				cba::GetColorEffectController().Shutdown();
			}
		}
		catch (...)
		{
		}
	}

	return TRUE;
}

extern "C" __declspec(dllexport) AddonDefinition* GetAddonDef()
{
	AddonDef.Signature = -78341;
	AddonDef.APIVersion = NEXUS_API_VERSION;
	AddonDef.Name = "cba4gw2";
#if defined(CBA_VER_MAJOR)
	// release.yml passes -DCBA_RELEASE_TAG=<the tag being built> (see
	// CMakeLists.txt), so a real release build's self-reported version
	// actually matches the GitHub tag Nexus's updater compares against -
	// found 2026-09-10 after Version.Major/Minor/Build/Revision sat frozen
	// at a hardcoded placeholder in every past release, so Nexus always
	// believed an update was available, even right after installing the
	// latest one (AddonVersion.cpp parses the tag as 3-part semver and
	// compares Major/Minor/Build against this struct - a version number
	// that never moves never satisfies that comparison).
	AddonDef.Version.Major = CBA_VER_MAJOR;
	AddonDef.Version.Minor = CBA_VER_MINOR;
	AddonDef.Version.Build = CBA_VER_BUILD;
	AddonDef.Version.Revision = 0;
#else
	AddonDef.Version.Major = 1;
	AddonDef.Version.Minor = 0;
#ifdef CBA_LOCAL_DEV
	// Simple +1-per-local-build counter (2026-09-11, was hour/minute*100+
	// second timestamp-derived until Emi pointed out that display read like
	// "build #5439" rather than a timestamp and asked for it to actually be
	// that) - lets Nexus's displayed version number prove which build is
	// really loaded, instead of eyeballing file sizes/timestamps (see
	// CLAUDE.md 2026-09-09). Regenerated by CMake's cba_gen_buildstamp
	// target on every build.
	AddonDef.Version.Build = CBA_BUILD_STAMP_COUNTER;
	AddonDef.Version.Revision = 0;
#else
	// Fallback for a CBA_LOCAL_DEV=OFF build made without CBA_RELEASE_TAG
	// (e.g. testing the release config locally) - old placeholder, unchanged
	// from before this fix so nothing regresses when the tag isn't passed.
	AddonDef.Version.Build = 2;
	AddonDef.Version.Revision = 0;
#endif
#endif
	AddonDef.Author = "Emisan01";
	AddonDef.Description =
		"Color balance, contrast enhancement and visual assist for Guild Wars 2. "
		"Applied via the Windows Magnification API.";
	AddonDef.Load = AddonLoad;
	AddonDef.Unload = AddonUnload;
	AddonDef.Flags = EAddonFlags_None;

	// CBA_LOCAL_DEV (CMake option, default ON) disables Nexus's own
	// auto-update for this addon during local iteration - found 2026-09-09
	// after a whole afternoon of Nexus silently reverting addons/cba.dll
	// back to the last published GitHub release (older than any local dev
	// build) despite fresh local builds landing correctly. Root cause was
	// this line: EUpdateProvider_GitHub tells Nexus to manage/update cba4gw2
	// FROM that repo, which is exactly wrong while iterating locally faster
	// than releases get cut. Ship builds (CBA_LOCAL_DEV=OFF) keep the real
	// GitHub-provider behavior end users should get.
#ifdef CBA_LOCAL_DEV
	AddonDef.Provider = EUpdateProvider_None;
#else
	AddonDef.Provider = EUpdateProvider_GitHub;
#endif
	AddonDef.UpdateLink = "https://github.com/Emisan01/cba4gw2";

	return &AddonDef;
}
